# Generated by Django 4.0.6 on 2022-12-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPlanner', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meeting_time', models.DateTimeField()),
                ('activity_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('Iamin', models.BooleanField(blank=True, null=True)),
                ('Iamout', models.BooleanField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupPlanner.groupactivities')),
            ],
        ),
    ]
