# Generated by Django 4.0.6 on 2022-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPlanner', '0003_groupactivities_activitystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupactivities',
            name='groupName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
