# Generated by Django 4.0.6 on 2022-12-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPlanner', '0005_groupactivities_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatus',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
