# Generated by Django 4.0.6 on 2022-12-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPlanner', '0006_activitystatus_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystatus',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='groupName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
